// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.HyChat.server.Handle.protoc;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MegBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MegBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 MegType = 1;</code>
     * @return The megType.
     */
    int getMegType();

    /**
     * <code>string time = 2;</code>
     * @return The time.
     */
    java.lang.String getTime();
    /**
     * <code>string time = 2;</code>
     * @return The bytes for time.
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>repeated bytes Body = 3;</code>
     * @return A list containing the body.
     */
    java.util.List<com.google.protobuf.ByteString> getBodyList();
    /**
     * <code>repeated bytes Body = 3;</code>
     * @return The count of body.
     */
    int getBodyCount();
    /**
     * <code>repeated bytes Body = 3;</code>
     * @param index The index of the element to return.
     * @return The body at the given index.
     */
    com.google.protobuf.ByteString getBody(int index);
  }
  /**
   * Protobuf type {@code MegBody}
   */
  public  static final class MegBody extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MegBody)
      MegBodyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MegBody.newBuilder() to construct.
    private MegBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MegBody() {
      time_ = "";
      body_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MegBody();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MegBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              megType_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              time_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                body_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              body_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          body_ = java.util.Collections.unmodifiableList(body_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.HyChat.server.Handle.protoc.Message.internal_static_MegBody_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.HyChat.server.Handle.protoc.Message.internal_static_MegBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.HyChat.server.Handle.protoc.Message.MegBody.class, com.HyChat.server.Handle.protoc.Message.MegBody.Builder.class);
    }

    public static final int MEGTYPE_FIELD_NUMBER = 1;
    private int megType_;
    /**
     * <code>int32 MegType = 1;</code>
     * @return The megType.
     */
    public int getMegType() {
      return megType_;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private volatile java.lang.Object time_;
    /**
     * <code>string time = 2;</code>
     * @return The time.
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <code>string time = 2;</code>
     * @return The bytes for time.
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> body_;
    /**
     * <code>repeated bytes Body = 3;</code>
     * @return A list containing the body.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getBodyList() {
      return body_;
    }
    /**
     * <code>repeated bytes Body = 3;</code>
     * @return The count of body.
     */
    public int getBodyCount() {
      return body_.size();
    }
    /**
     * <code>repeated bytes Body = 3;</code>
     * @param index The index of the element to return.
     * @return The body at the given index.
     */
    public com.google.protobuf.ByteString getBody(int index) {
      return body_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (megType_ != 0) {
        output.writeInt32(1, megType_);
      }
      if (!getTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, time_);
      }
      for (int i = 0; i < body_.size(); i++) {
        output.writeBytes(3, body_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (megType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, megType_);
      }
      if (!getTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, time_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < body_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(body_.get(i));
        }
        size += dataSize;
        size += 1 * getBodyList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.HyChat.server.Handle.protoc.Message.MegBody)) {
        return super.equals(obj);
      }
      com.HyChat.server.Handle.protoc.Message.MegBody other = (com.HyChat.server.Handle.protoc.Message.MegBody) obj;

      if (getMegType()
          != other.getMegType()) return false;
      if (!getTime()
          .equals(other.getTime())) return false;
      if (!getBodyList()
          .equals(other.getBodyList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMegType();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      if (getBodyCount() > 0) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBodyList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.HyChat.server.Handle.protoc.Message.MegBody parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HyChat.server.Handle.protoc.Message.MegBody parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HyChat.server.Handle.protoc.Message.MegBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HyChat.server.Handle.protoc.Message.MegBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HyChat.server.Handle.protoc.Message.MegBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HyChat.server.Handle.protoc.Message.MegBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HyChat.server.Handle.protoc.Message.MegBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HyChat.server.Handle.protoc.Message.MegBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HyChat.server.Handle.protoc.Message.MegBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.HyChat.server.Handle.protoc.Message.MegBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HyChat.server.Handle.protoc.Message.MegBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HyChat.server.Handle.protoc.Message.MegBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.HyChat.server.Handle.protoc.Message.MegBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MegBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MegBody)
        com.HyChat.server.Handle.protoc.Message.MegBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.HyChat.server.Handle.protoc.Message.internal_static_MegBody_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.HyChat.server.Handle.protoc.Message.internal_static_MegBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.HyChat.server.Handle.protoc.Message.MegBody.class, com.HyChat.server.Handle.protoc.Message.MegBody.Builder.class);
      }

      // Construct using com.HyChat.server.Handle.protoc.Message.MegBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        megType_ = 0;

        time_ = "";

        body_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.HyChat.server.Handle.protoc.Message.internal_static_MegBody_descriptor;
      }

      @java.lang.Override
      public com.HyChat.server.Handle.protoc.Message.MegBody getDefaultInstanceForType() {
        return com.HyChat.server.Handle.protoc.Message.MegBody.getDefaultInstance();
      }

      @java.lang.Override
      public com.HyChat.server.Handle.protoc.Message.MegBody build() {
        com.HyChat.server.Handle.protoc.Message.MegBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.HyChat.server.Handle.protoc.Message.MegBody buildPartial() {
        com.HyChat.server.Handle.protoc.Message.MegBody result = new com.HyChat.server.Handle.protoc.Message.MegBody(this);
        int from_bitField0_ = bitField0_;
        result.megType_ = megType_;
        result.time_ = time_;
        if (((bitField0_ & 0x00000001) != 0)) {
          body_ = java.util.Collections.unmodifiableList(body_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.HyChat.server.Handle.protoc.Message.MegBody) {
          return mergeFrom((com.HyChat.server.Handle.protoc.Message.MegBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.HyChat.server.Handle.protoc.Message.MegBody other) {
        if (other == com.HyChat.server.Handle.protoc.Message.MegBody.getDefaultInstance()) return this;
        if (other.getMegType() != 0) {
          setMegType(other.getMegType());
        }
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          onChanged();
        }
        if (!other.body_.isEmpty()) {
          if (body_.isEmpty()) {
            body_ = other.body_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBodyIsMutable();
            body_.addAll(other.body_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.HyChat.server.Handle.protoc.Message.MegBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.HyChat.server.Handle.protoc.Message.MegBody) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int megType_ ;
      /**
       * <code>int32 MegType = 1;</code>
       * @return The megType.
       */
      public int getMegType() {
        return megType_;
      }
      /**
       * <code>int32 MegType = 1;</code>
       * @param value The megType to set.
       * @return This builder for chaining.
       */
      public Builder setMegType(int value) {
        
        megType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 MegType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMegType() {
        
        megType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>string time = 2;</code>
       * @return The time.
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string time = 2;</code>
       * @return The bytes for time.
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string time = 2;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>string time = 2;</code>
       * @param value The bytes for time to set.
       * @return This builder for chaining.
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        time_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> body_ = java.util.Collections.emptyList();
      private void ensureBodyIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          body_ = new java.util.ArrayList<com.google.protobuf.ByteString>(body_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes Body = 3;</code>
       * @return A list containing the body.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getBodyList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(body_) : body_;
      }
      /**
       * <code>repeated bytes Body = 3;</code>
       * @return The count of body.
       */
      public int getBodyCount() {
        return body_.size();
      }
      /**
       * <code>repeated bytes Body = 3;</code>
       * @param index The index of the element to return.
       * @return The body at the given index.
       */
      public com.google.protobuf.ByteString getBody(int index) {
        return body_.get(index);
      }
      /**
       * <code>repeated bytes Body = 3;</code>
       * @param index The index to set the value at.
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBodyIsMutable();
        body_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes Body = 3;</code>
       * @param value The body to add.
       * @return This builder for chaining.
       */
      public Builder addBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBodyIsMutable();
        body_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes Body = 3;</code>
       * @param values The body to add.
       * @return This builder for chaining.
       */
      public Builder addAllBody(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureBodyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, body_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes Body = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        body_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MegBody)
    }

    // @@protoc_insertion_point(class_scope:MegBody)
    private static final com.HyChat.server.Handle.protoc.Message.MegBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.HyChat.server.Handle.protoc.Message.MegBody();
    }

    public static com.HyChat.server.Handle.protoc.Message.MegBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MegBody>
        PARSER = new com.google.protobuf.AbstractParser<MegBody>() {
      @java.lang.Override
      public MegBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MegBody(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MegBody> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MegBody> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.HyChat.server.Handle.protoc.Message.MegBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MegBody_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MegBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\"6\n\007MegBody\022\017\n\007MegType\030\001 " +
      "\001(\005\022\014\n\004time\030\002 \001(\t\022\014\n\004Body\030\003 \003(\014B!\n\037com.H" +
      "yChat.server.Handle.protocb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MegBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MegBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MegBody_descriptor,
        new java.lang.String[] { "MegType", "Time", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
