// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReqMessage.proto

package com.HyChat.server.Message;

public final class ReqMessage {
  private ReqMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MegBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MegBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 MegType = 1;</code>
     * @return The megType.
     */
    int getMegType();

    /**
     * <pre>
     *是否群发
     * </pre>
     *
     * <code>bool IsMass = 6;</code>
     * @return The isMass.
     */
    boolean getIsMass();

    /**
     * <pre>
     *目标用户
     * </pre>
     *
     * <code>string Target = 4;</code>
     * @return The target.
     */
    java.lang.String getTarget();
    /**
     * <pre>
     *目标用户
     * </pre>
     *
     * <code>string Target = 4;</code>
     * @return The bytes for target.
     */
    com.google.protobuf.ByteString
        getTargetBytes();

    /**
     * <code>string token = 5;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 5;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 2;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 2;</code>
     * @return The time.
     */
    com.google.protobuf.Timestamp getTime();
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();

    /**
     * <code>bytes Body = 3;</code>
     * @return The body.
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * <pre>
   *客户端发送的给服务器的消息
   * </pre>
   *
   * Protobuf type {@code MegBody}
   */
  public  static final class MegBody extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MegBody)
      MegBodyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MegBody.newBuilder() to construct.
    private MegBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MegBody() {
      target_ = "";
      token_ = "";
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MegBody();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MegBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              megType_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (time_ != null) {
                subBuilder = time_.toBuilder();
              }
              time_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(time_);
                time_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {

              body_ = input.readBytes();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              target_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 48: {

              isMass_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.HyChat.server.Message.ReqMessage.internal_static_MegBody_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.HyChat.server.Message.ReqMessage.internal_static_MegBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.HyChat.server.Message.ReqMessage.MegBody.class, com.HyChat.server.Message.ReqMessage.MegBody.Builder.class);
    }

    public static final int MEGTYPE_FIELD_NUMBER = 1;
    private int megType_;
    /**
     * <code>int32 MegType = 1;</code>
     * @return The megType.
     */
    public int getMegType() {
      return megType_;
    }

    public static final int ISMASS_FIELD_NUMBER = 6;
    private boolean isMass_;
    /**
     * <pre>
     *是否群发
     * </pre>
     *
     * <code>bool IsMass = 6;</code>
     * @return The isMass.
     */
    public boolean getIsMass() {
      return isMass_;
    }

    public static final int TARGET_FIELD_NUMBER = 4;
    private volatile java.lang.Object target_;
    /**
     * <pre>
     *目标用户
     * </pre>
     *
     * <code>string Target = 4;</code>
     * @return The target.
     */
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        target_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *目标用户
     * </pre>
     *
     * <code>string Target = 4;</code>
     * @return The bytes for target.
     */
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 5;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 5;</code>
     * @return The token.
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 5;</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp time_;
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 2;</code>
     * @return Whether the time field is set.
     */
    public boolean hasTime() {
      return time_ != null;
    }
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 2;</code>
     * @return The time.
     */
    public com.google.protobuf.Timestamp getTime() {
      return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
    }
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp time = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
      return getTime();
    }

    public static final int BODY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes Body = 3;</code>
     * @return The body.
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (megType_ != 0) {
        output.writeInt32(1, megType_);
      }
      if (time_ != null) {
        output.writeMessage(2, getTime());
      }
      if (!body_.isEmpty()) {
        output.writeBytes(3, body_);
      }
      if (!getTargetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, target_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, token_);
      }
      if (isMass_ != false) {
        output.writeBool(6, isMass_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (megType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, megType_);
      }
      if (time_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTime());
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, body_);
      }
      if (!getTargetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, target_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, token_);
      }
      if (isMass_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isMass_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.HyChat.server.Message.ReqMessage.MegBody)) {
        return super.equals(obj);
      }
      com.HyChat.server.Message.ReqMessage.MegBody other = (com.HyChat.server.Message.ReqMessage.MegBody) obj;

      if (getMegType()
          != other.getMegType()) return false;
      if (getIsMass()
          != other.getIsMass()) return false;
      if (!getTarget()
          .equals(other.getTarget())) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (hasTime() != other.hasTime()) return false;
      if (hasTime()) {
        if (!getTime()
            .equals(other.getTime())) return false;
      }
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMegType();
      hash = (37 * hash) + ISMASS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsMass());
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getTarget().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
      }
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.HyChat.server.Message.ReqMessage.MegBody parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HyChat.server.Message.ReqMessage.MegBody parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HyChat.server.Message.ReqMessage.MegBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HyChat.server.Message.ReqMessage.MegBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HyChat.server.Message.ReqMessage.MegBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HyChat.server.Message.ReqMessage.MegBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HyChat.server.Message.ReqMessage.MegBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HyChat.server.Message.ReqMessage.MegBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HyChat.server.Message.ReqMessage.MegBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.HyChat.server.Message.ReqMessage.MegBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HyChat.server.Message.ReqMessage.MegBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HyChat.server.Message.ReqMessage.MegBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.HyChat.server.Message.ReqMessage.MegBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *客户端发送的给服务器的消息
     * </pre>
     *
     * Protobuf type {@code MegBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MegBody)
        com.HyChat.server.Message.ReqMessage.MegBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.HyChat.server.Message.ReqMessage.internal_static_MegBody_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.HyChat.server.Message.ReqMessage.internal_static_MegBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.HyChat.server.Message.ReqMessage.MegBody.class, com.HyChat.server.Message.ReqMessage.MegBody.Builder.class);
      }

      // Construct using com.HyChat.server.Message.ReqMessage.MegBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        megType_ = 0;

        isMass_ = false;

        target_ = "";

        token_ = "";

        if (timeBuilder_ == null) {
          time_ = null;
        } else {
          time_ = null;
          timeBuilder_ = null;
        }
        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.HyChat.server.Message.ReqMessage.internal_static_MegBody_descriptor;
      }

      @java.lang.Override
      public com.HyChat.server.Message.ReqMessage.MegBody getDefaultInstanceForType() {
        return com.HyChat.server.Message.ReqMessage.MegBody.getDefaultInstance();
      }

      @java.lang.Override
      public com.HyChat.server.Message.ReqMessage.MegBody build() {
        com.HyChat.server.Message.ReqMessage.MegBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.HyChat.server.Message.ReqMessage.MegBody buildPartial() {
        com.HyChat.server.Message.ReqMessage.MegBody result = new com.HyChat.server.Message.ReqMessage.MegBody(this);
        result.megType_ = megType_;
        result.isMass_ = isMass_;
        result.target_ = target_;
        result.token_ = token_;
        if (timeBuilder_ == null) {
          result.time_ = time_;
        } else {
          result.time_ = timeBuilder_.build();
        }
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.HyChat.server.Message.ReqMessage.MegBody) {
          return mergeFrom((com.HyChat.server.Message.ReqMessage.MegBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.HyChat.server.Message.ReqMessage.MegBody other) {
        if (other == com.HyChat.server.Message.ReqMessage.MegBody.getDefaultInstance()) return this;
        if (other.getMegType() != 0) {
          setMegType(other.getMegType());
        }
        if (other.getIsMass() != false) {
          setIsMass(other.getIsMass());
        }
        if (!other.getTarget().isEmpty()) {
          target_ = other.target_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.hasTime()) {
          mergeTime(other.getTime());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.HyChat.server.Message.ReqMessage.MegBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.HyChat.server.Message.ReqMessage.MegBody) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int megType_ ;
      /**
       * <code>int32 MegType = 1;</code>
       * @return The megType.
       */
      public int getMegType() {
        return megType_;
      }
      /**
       * <code>int32 MegType = 1;</code>
       * @param value The megType to set.
       * @return This builder for chaining.
       */
      public Builder setMegType(int value) {
        
        megType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 MegType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMegType() {
        
        megType_ = 0;
        onChanged();
        return this;
      }

      private boolean isMass_ ;
      /**
       * <pre>
       *是否群发
       * </pre>
       *
       * <code>bool IsMass = 6;</code>
       * @return The isMass.
       */
      public boolean getIsMass() {
        return isMass_;
      }
      /**
       * <pre>
       *是否群发
       * </pre>
       *
       * <code>bool IsMass = 6;</code>
       * @param value The isMass to set.
       * @return This builder for chaining.
       */
      public Builder setIsMass(boolean value) {
        
        isMass_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否群发
       * </pre>
       *
       * <code>bool IsMass = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsMass() {
        
        isMass_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object target_ = "";
      /**
       * <pre>
       *目标用户
       * </pre>
       *
       * <code>string Target = 4;</code>
       * @return The target.
       */
      public java.lang.String getTarget() {
        java.lang.Object ref = target_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          target_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *目标用户
       * </pre>
       *
       * <code>string Target = 4;</code>
       * @return The bytes for target.
       */
      public com.google.protobuf.ByteString
          getTargetBytes() {
        java.lang.Object ref = target_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          target_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *目标用户
       * </pre>
       *
       * <code>string Target = 4;</code>
       * @param value The target to set.
       * @return This builder for chaining.
       */
      public Builder setTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标用户
       * </pre>
       *
       * <code>string Target = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTarget() {
        
        target_ = getDefaultInstance().getTarget();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标用户
       * </pre>
       *
       * <code>string Target = 4;</code>
       * @param value The bytes for target to set.
       * @return This builder for chaining.
       */
      public Builder setTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        target_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 5;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 5;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 5;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 5;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp time_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeBuilder_;
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 2;</code>
       * @return Whether the time field is set.
       */
      public boolean hasTime() {
        return timeBuilder_ != null || time_ != null;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 2;</code>
       * @return The time.
       */
      public com.google.protobuf.Timestamp getTime() {
        if (timeBuilder_ == null) {
          return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
        } else {
          return timeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 2;</code>
       */
      public Builder setTime(com.google.protobuf.Timestamp value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          time_ = value;
          onChanged();
        } else {
          timeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 2;</code>
       */
      public Builder setTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timeBuilder_ == null) {
          time_ = builderForValue.build();
          onChanged();
        } else {
          timeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 2;</code>
       */
      public Builder mergeTime(com.google.protobuf.Timestamp value) {
        if (timeBuilder_ == null) {
          if (time_ != null) {
            time_ =
              com.google.protobuf.Timestamp.newBuilder(time_).mergeFrom(value).buildPartial();
          } else {
            time_ = value;
          }
          onChanged();
        } else {
          timeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 2;</code>
       */
      public Builder clearTime() {
        if (timeBuilder_ == null) {
          time_ = null;
          onChanged();
        } else {
          time_ = null;
          timeBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimeBuilder() {
        
        onChanged();
        return getTimeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
        if (timeBuilder_ != null) {
          return timeBuilder_.getMessageOrBuilder();
        } else {
          return time_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : time_;
        }
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp time = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTime(),
                  getParentForChildren(),
                  isClean());
          time_ = null;
        }
        return timeBuilder_;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes Body = 3;</code>
       * @return The body.
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes Body = 3;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes Body = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MegBody)
    }

    // @@protoc_insertion_point(class_scope:MegBody)
    private static final com.HyChat.server.Message.ReqMessage.MegBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.HyChat.server.Message.ReqMessage.MegBody();
    }

    public static com.HyChat.server.Message.ReqMessage.MegBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MegBody>
        PARSER = new com.google.protobuf.AbstractParser<MegBody>() {
      @java.lang.Override
      public MegBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MegBody(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MegBody> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MegBody> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.HyChat.server.Message.ReqMessage.MegBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MegBody_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MegBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ReqMessage.proto\032\037google/protobuf/time" +
      "stamp.proto\"\201\001\n\007MegBody\022\017\n\007MegType\030\001 \001(\005" +
      "\022\016\n\006IsMass\030\006 \001(\010\022\016\n\006Target\030\004 \001(\t\022\r\n\005toke" +
      "n\030\005 \001(\t\022(\n\004time\030\002 \001(\0132\032.google.protobuf." +
      "Timestamp\022\014\n\004Body\030\003 \001(\014B\033\n\031com.HyChat.se" +
      "rver.Messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_MegBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MegBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MegBody_descriptor,
        new java.lang.String[] { "MegType", "IsMass", "Target", "Token", "Time", "Body", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
